# Oregon Trail game transcribed to Python from original BASIC code.

# Input for instructions
x = input("Do you need instructions? (Y/N) ")
if (x == "Y") or (x == "y"):
    print("This program simulates a trip over the Oregon Trail from\nIndependence, Missouri to Oregon City, Oregon in 1847.\nYour family of five will cover the 2040 mile Oregon Trail\nin 5-6 months --- if you make it alive.\n\nYou have saved $900 to spend for the trip, and you've just\npaid $200 for a wagon. You will need to spend the rest of\nyour money on the following items:\n\n\tOxen - you can spend $200-$300 on your team.\n\t\tThe more you spend the faster you'll go\n\t\tbecause you'll have better animals.\n\n\tFood - the more you have, the less chance there\n\t\tis of getting sick.\n\n\tAmmunition - $1 buys a belt of 50 bullets.\n\t\tYou will need bullets for attacks by animals\n\t\tand bandits, and for hunting food.\n\n\tClothing - This is especially important for the cold\n\t\tweather you will encounter when crossing the\n\t\tmountains.\n\n\tMiscellaneous Supplies - This includes medicine and\n\t\tother things you will need for sickness\n\t\tand emergency repairs.\n\nYou can spend all your money before you start your trip or\nyou can save some of your cash to spend at forts along\nthe way when you run low. However, items cost more at\nthe forts. You can also go hunting along the way to get\nmore food.\n\nWhenever you have to use your trusty rifle along the way,\nyou will be told to type in a word (one that sounds like a\ngun shot). The faster you type in that word and this the\n\'Enter\' key, the better luck you'll have with your gun.\n\nAt each turn, all items are shown in dollar amount\nexcept bullets.\nGood luck!!!");
else:
    #Set shooting expertise level
    print("1 = Ace Marksman 2=Good Shot 3 = Fair to middlin'\n\t4 = Need More Practice 5 = Shaky Knees\nEnter one of the above -- The better you claim you are, the\nfaster you'll have to be with your gun to be successful.")
